/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2022-03-13 14:37:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.contacess;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import backendxpto20202.modelo.bean.Usuario;
import backendxpto20202.controle.ControleUsuario;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/contacess/../../inc/materalizeWeb.inc", Long.valueOf(1602890481427L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("backendxpto20202.modelo.bean.Usuario");
    _jspx_imports_classes.add("backendxpto20202.controle.ControleUsuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String login = request.getParameter("LOGIN");
    String senha = request.getParameter("SENHA");
    Usuario usu = new Usuario(login,senha);
    ControleUsuario usucont = new ControleUsuario();
    usu = usucont.valida(usu);
    session.setAttribute("UsuarioLogado",usu);

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    ");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <!-- Compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.css\">\r\n");
      out.write("    <!-- Compiled and minified JavaScript -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-2.2.2.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.js\"></script>\r\n");
      out.write("</head>");
      out.write("\n");
      out.write("    <title>SISTEMA </title>\n");
      out.write("    <body>\n");
      out.write("        ");
 if (usu != null) { 
      out.write("\n");
      out.write("            <!-- Dropdown1 Trigger -->\n");
      out.write("            <a class='dropdown-button btn' data-beloworigin=\"true\" href='#' data-activates='dropdown1'>Manter Usuário</a>        \n");
      out.write("            <a class='dropdown-button btn' data-beloworigin=\"true\" href='#' data-activates='dropdown2'>Manter Pessoa</a>        \n");
      out.write("            <a class='dropdown-button btn' data-beloworigin=\"true\" href='#' data-activates='dropdown3'>Manter Controle de Acesso</a>        \n");
      out.write("            <a class='dropdown-button btn' data-beloworigin=\"true\" href='#' data-activates='dropdown4'>Manter Funcionario</a>    \n");
      out.write("            <a class='dropdown-button btn' data-beloworigin=\"true\" href='#' data-activates='dropdown5'>Manter Unidade</a>        \n");
      out.write("            <a class='dropdown-button btn' data-beloworigin=\"true\" href='#' data-activates='dropdown6'>Manter Funcionario e Desempenho</a>  \n");
      out.write("\n");
      out.write("            ");
 if (usu.getTipo().equals("ADM")) { 
      out.write("\n");
      out.write("                <!-- Dropdown1 Structure -->\n");
      out.write("                <ul id='dropdown1' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../usuario/inserirUsuario.jsp\"> InseriUsuario </a></li>\n");
      out.write("                    <li><a href=\"../usuario/consultarUsuario.jsp\"> ConsultaUsuarioParametro </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <ul id='dropdown1' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../usuario/consultarUsuario.jsp\"> ConsultaUsuarioParametro </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            ");
 if (usu.getTipo().equals("ADM")) { 
      out.write("\n");
      out.write("                <!-- Dropdown2 Structure -->\n");
      out.write("                <ul id='dropdown2' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../pessoa/inserirPessoa.jsp\"> InseriPessoa </a></li>\n");
      out.write("                    <li><a href=\"../pessoa/consultarPessoa.jsp\"> ConsultaPessoa </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <ul id='dropdown2' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../pessoa/consultarPessoa.jsp\"> ConsultaPessoa </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            ");
 if (usu.getTipo().equals("ADM")) { 
      out.write("\n");
      out.write("                <!-- Dropdown3 Structure -->\n");
      out.write("                <ul id='dropdown3' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../usupes/inserirRelacaoUsuarioPessoa.jsp\"> InseriUsuarioPessoa </a></li>\n");
      out.write("                    <li><a href=\"../usupes/consultarRelacaoUsuarioPessoa.jsp\"> ConsultaUsuarioPessoa </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <ul id='dropdown3' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../usuario/consultarUsuarioPessoa.jsp\"> ConsultaUsuarioPessoa </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            ");
 if (usu.getTipo().equals("ADM")) { 
      out.write("\n");
      out.write("                <!-- Dropdown3 Structure -->\n");
      out.write("                <ul id='dropdown4' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../Funcionarios/inserirFuncionario.jsp\"> InseriFuncionario </a></li>\n");
      out.write("                    <li><a href=\"../Funcionarios/consultarFuncionario.jsp\"> ConsultaFuncionario </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <ul id='dropdown4' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../Funcionarios/consultarFuncionario.jsp\"> ConsultaFuncionario </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("             ");
 if (usu.getTipo().equals("ADM")) { 
      out.write("\n");
      out.write("                <!-- Dropdown3 Structure -->\n");
      out.write("                <ul id='dropdown5' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../Unidade/inserirUnidade.jsp\"> InseriUnidade </a></li>\n");
      out.write("                    <li><a href=\"../Unidade/consultarUnidade.jsp\"> ConsultaUnidade </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <ul id='dropdown5' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../Unidade/consultarUnidade.jsp\"> ConsultaUnidade </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("             ");
 if (usu.getTipo().equals("ADM")) { 
      out.write("\n");
      out.write("                <!-- Dropdown3 Structure -->\n");
      out.write("                <ul id='dropdown6' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../FuncionarioUnidade/inserirFuncionarioUni.jsp\"> Inserir Funcionario Desempenho</a></li>\n");
      out.write("                    <li><a href=\"../FuncionarioUnidade/consultaFunUni.jsp\"> Consulta Funcionario Desempenho </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <ul id='dropdown6' class='dropdown-content'>\n");
      out.write("                    <li><a href=\"../FuncionarioUnidade/consultaFunUni.jsp\"> Consulta Funcionario Desempenho </a></li>\n");
      out.write("                </ul>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <h1>USUÁRIO INVÁLIDO</h1>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
